/* eslint-disable */
// Generated by Wrangler by running `wrangler --config=wrangler.json types --include-runtime false` (hash: d796375d04f78ff7cadb4985842cf129)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index')
    durableNamespaces: 'Sandbox'
  }
  interface Env {
    NODE_ENV: string
    ENVIRONMENT: string
    WS_PORT: string
    CLOUDFLARE_ACCOUNT_ID: string
    CLOUDFLARE_API_TOKEN: string
    Sandbox: DurableObjectNamespace<import('./src/index').Sandbox>
    RATE_LIMITER: RateLimit
    Web: Fetcher
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'NODE_ENV'
        | 'ENVIRONMENT'
        | 'WS_PORT'
        | 'CLOUDFLARE_ACCOUNT_ID'
        | 'CLOUDFLARE_API_TOKEN'
      >
    > {}
}
