/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as CommandRouteRouteImport } from './routes/command/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWsRouteImport } from './routes/api/ws'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiExecRouteImport } from './routes/api/exec'
import { Route as ApiDestroyRouteImport } from './routes/api/destroy'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRouteRoute = CommandRouteRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecRoute = ApiExecRouteImport.update({
  id: '/api/exec',
  path: '/api/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDestroyRoute = ApiDestroyRouteImport.update({
  id: '/api/destroy',
  path: '/api/destroy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRouteRoute
  '/docs': typeof DocsRouteRoute
  '/api/destroy': typeof ApiDestroyRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reset': typeof ApiResetRoute
  '/api/version': typeof ApiVersionRoute
  '/api/ws': typeof ApiWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRouteRoute
  '/docs': typeof DocsRouteRoute
  '/api/destroy': typeof ApiDestroyRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reset': typeof ApiResetRoute
  '/api/version': typeof ApiVersionRoute
  '/api/ws': typeof ApiWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRouteRoute
  '/docs': typeof DocsRouteRoute
  '/api/destroy': typeof ApiDestroyRoute
  '/api/exec': typeof ApiExecRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reset': typeof ApiResetRoute
  '/api/version': typeof ApiVersionRoute
  '/api/ws': typeof ApiWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/docs'
    | '/api/destroy'
    | '/api/exec'
    | '/api/health'
    | '/api/reset'
    | '/api/version'
    | '/api/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/docs'
    | '/api/destroy'
    | '/api/exec'
    | '/api/health'
    | '/api/reset'
    | '/api/version'
    | '/api/ws'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/docs'
    | '/api/destroy'
    | '/api/exec'
    | '/api/health'
    | '/api/reset'
    | '/api/version'
    | '/api/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRouteRoute: typeof CommandRouteRoute
  DocsRouteRoute: typeof DocsRouteRoute
  ApiDestroyRoute: typeof ApiDestroyRoute
  ApiExecRoute: typeof ApiExecRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiWsRoute: typeof ApiWsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exec': {
      id: '/api/exec'
      path: '/api/exec'
      fullPath: '/api/exec'
      preLoaderRoute: typeof ApiExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/destroy': {
      id: '/api/destroy'
      path: '/api/destroy'
      fullPath: '/api/destroy'
      preLoaderRoute: typeof ApiDestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRouteRoute: CommandRouteRoute,
  DocsRouteRoute: DocsRouteRoute,
  ApiDestroyRoute: ApiDestroyRoute,
  ApiExecRoute: ApiExecRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiResetRoute: ApiResetRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiWsRoute: ApiWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
